[tools]
java = { version = "oracle-graalvm-24.0.1", release_type = "ea" }
"asdf:joschi/asdf-mvnd" = "latest"

node = { version = "latest", postinstall = "corepack enable pnpm" }
ruby = { version = "latest", postinstall = "ruby-post-install" }
usage = "latest"

"pipx:opentype-feature-freezer" = "latest"
"pipx:yt-dlp" = "latest"
"pipx:streamlink" = "latest"
gradle = "latest"
uv = "latest"
cargo-binstall = "latest"
"cargo:eza" = "latest"
"cargo:skim" = "latest"
"cargo:ripgrep" = "latest"
"pipx:pytest" = "latest"
erlang = "latest"
elixir = "latest"
"cargo:fd-find" = "latest"

[settings]
experimental = true
idiomatic_version_file_enable_tools = ["ruby", "node"]

[settings.python]
uv_venv_auto = false
